/**
 * campaign
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface FaceComparison {
    /**
     * 用户的AppUserId
     */
    userId?: string;

    /**
     * 微信的用户OpenID
     */
    openId?: string;

    /**
     * 微信的用户昵称
     */
    nickName?: string;

    /**
     * 微信的用户头像
     */
    headerImgUrl?: string;

    /**
     * 微信的用户国家
     */
    country?: string;

    comparisonId?: string;

    /**
     * 相似度
     */
    confidence?: number;

    /**
     * 点评数
     */
    commentCount?: number;

    ranking?: number;

    img1Url?: string;

    img2Url?: string;

    errcode?: number;

    errmsg?: string;

}
