/**
 * campaign
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 提交海报数据
 */
export interface StatisticDataEntity {
    /**
     * 用户的AppUserId
     */
    userId?: string;

    /**
     * Base64海报图  格式如：data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wB....
     */
    img?: string;

    /**
     * 微信的用户OpenID
     */
    openid?: string;

    /**
     * 微信的用户昵称
     */
    nickname?: string;

    /**
     * 微信的用户头像
     */
    headimgurl?: string;

    /**
     * 微信的用户国家
     */
    country?: string;

}
